apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: devops-stack
spec:
  generators:
  - git:
      directories:
      - path: '**/**'
      repoURL: https://github.com/csepulveda/homelab.git
      revision: main
  goTemplate: true
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      destination:
        name: in-cluster
        namespace: '{{index .path.segments 0}}'
      project: default
      sources:
      - helm:
          releaseName: '{{.path.basename}}'
          valueFiles:
          - values.yaml
        path: '{{.path.path}}'
        repoURL: https://github.com/csepulveda/homelab.git
        targetRevision: main
  templatePatch: |
    spec:
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          {{- if eq .path.basename "stackgres-operator" }}
          - ServerSideApply=true
          {{- end }}
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true