apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: devops-stack
spec:
  generators:
  - git:
      directories:
      - path: '**/**'
      repoURL: https://github.com/csepulveda/homelab.git
      revision: main
  goTemplate: true
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      destination:
        name: in-cluster
        namespace: '{{index .path.segments 0}}'
      project: default
      sources:
      - helm:
          releaseName: '{{.path.basename}}'
          valueFiles:
          - values.yaml
        path: '{{.path.path}}'
        repoURL: https://github.com/csepulveda/homelab.git
        targetRevision: main
  templatePatch: |
    spec:
      {{- if eq .path.basename "cilium" }}
      ignoreDifferences:
        - group: ""
          kind: Service
          jsonPointers:
            - /spec/ports/0/nodePort
            - /spec/ports/1/nodePort
      {{- end }}
      {{- if eq .path.basename "immich" }}
      ignoreDifferences:
        - group: apps
          kind: Deployment
          jsonPointers:
            - /spec/replicas
      {{- end }}
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          {{- if or (eq .path.basename "stackgres-operator") (eq .path.basename "cilium") (eq .path.basename "minio")  (eq .path.basename "kube") }}
          - ServerSideApply=true
          {{- end }}
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true