apiVersion: v2
name: minio
description: install minio
type: application
version: 17.3.0
appVersion: 2025.6.13

dependencies:
- name: minio
  version: 5.3.0
  repository: "https://charts.min.io"
  alias: minio
