minio:
  auth:
    existingSecret: admin-creds
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  ingress:
    enabled: true
    hostname: s3.csepulveda.net
    ingressClassName: cilium
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      external-dns.alpha.kubernetes.io/target: router.csepulveda.net
    tls: true

  console:
    ingress:
      enabled: true
      hostname: minio.csepulveda.net
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      tls: true
  
  persistence:
    storageClass: iscsi
    size: 32Gi
