minio:
  # Mode: standalone
  mode: standalone
  
  # Replicas for standalone mode
  replicas: 1
  
  # Root credentials - using existing secret
  existingSecret: admin-creds
  existingSecretUserKey: root-user
  existingSecretPasswordKey: root-password
  
  # Resources
  resources:
    requests:
      memory: 512Mi
  
  # Persistence - single volume for standalone
  persistence:
    enabled: true
    storageClass: iscsi
    size: 32Gi
    accessMode: ReadWriteOnce
  
  # Service
  service:
    type: ClusterIP
    port: 9000
    consolePort: 9001
  
  # Ingress for MinIO API
  ingress:
    enabled: true
    ingressClassName: cilium
    hosts:
      - s3.csepulveda.net
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      external-dns.alpha.kubernetes.io/target: router.csepulveda.net
    tls:
      - secretName: minio-api-tls
        hosts:
          - s3.csepulveda.net
  
  # Console Ingress
  consoleIngress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - minio.csepulveda.net
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    tls:
      - secretName: minio-console-tls
        hosts:
          - minio.csepulveda.net
  
  # Metrics
  metrics:
    serviceMonitor:
      enabled: true
      includeNode: true
  
  # Environment variables
  environment:
    MINIO_BROWSER: "on"
    MINIO_BROWSER_REDIRECT_URL: "https://minio.csepulveda.net"