apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbitt-config
  namespace: multimedia
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: multimedia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      - name: qbittorrent
        image: linuxserver/qbittorrent
        resources:
          limits:
            memory: "2Gi"
          requests:
            memory: "512Mi"
        env:
        - name: PUID
          value: "1057" 
        - name: PGID
          value: "1056"  
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
        ports:
        - containerPort: 8080
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: qbitt-config
      - name: downloads
        persistentVolumeClaim:
          claimName: qbitt-download
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: multimedia
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: qbittorrent  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  name: qbittorrent
  namespace: multimedia
spec:
  ingressClassName: nginx
  rules:
  - host: qbittorrent.csepulveda.net
    http:
      paths:
      - backend:
          service:
            name: qbittorrent
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - qbittorrent.csepulveda.net
    secretName: qbittorrent.csepulveda.net-tls
