apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: cesar.sepulveda.b@gmail.com
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          email: cesar.sepulveda.b@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token