apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  name: stackgres
  namespace: stackgres
spec:
  ingressClassName: nginx
  rules:
  - host: rds.csepulveda.net
    http:
      paths:
      - backend:
          service:
            name: stackgres-restapi
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - rds.csepulveda.net
    secretName: rds.csepulveda.net-tls