apiVersion: stackgres.io/v1
kind: SGPostgresConfig
metadata:
  name: immich-config
  namespace: immich
spec:
  postgresVersion: "14"
  postgresql.conf:
    shared_preload_libraries: "pg_stat_statements, auto_explain, vectors"
---
apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: immich-postgresql
  namespace: immich
spec:
  managedSql:
  instances: 3
  postgres:
    version: 14.17
    extensions:
      - name: cube
      - name: earthdistance
      - name: vector
      - name: uuid-ossp
      - name: pg_trgm
      - name: unaccent
      - name: vectors
        version: 0.3.0
  configurations:
    sgPostgresConfig: immich-config
  pods:
    persistentVolume: 
      size: 10Gi