apiVersion: stackgres.io/v1
kind: SGInstanceProfile
metadata:
  annotations:
  name: immich-db-2g
  namespace: immich
spec:
  cpu: "1"
  memory: 2Gi
  requests:
    cpu: "1"
    memory: 2Gi
---
apiVersion: stackgres.io/v1
kind: SGPostgresConfig
metadata:
  name: immich-config
  namespace: immich
spec:
  postgresVersion: "14"
  postgresql.conf:
    shared_preload_libraries: "pg_stat_statements, auto_explain, vectors"
---
apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: immich-postgresql
  namespace: immich
spec:
  instances: 2
  postgres:
    version: "14.17"
    extensions:
      - name: cube
      - name: earthdistance
      - name: vector
      - name: uuid-ossp
      - name: pg_trgm
      - name: unaccent
      - name: vectors
  configurations:
    sgPostgresConfig: immich-config
  sgInstanceProfile: immich-db-2g
  pods:
    persistentVolume: 
      size: 10Gi
