tempo:
  global:
    extraEnv:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: tempo-bucket
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: tempo-bucket
          key: AWS_SECRET_ACCESS_KEY
  config: |
    storage:
      trace:
        backend: s3
        s3:
          endpoint: http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc.cluster.local:80
          bucket: tempo-bucket
          region: us-east-1
          forcepathstyle: true
          insecure: true
  metaMonitoring:
    serviceMonitor:
      enabled: true
  tempo:
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 512Mi