tempo:
  global:
    extraEnv:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: tempo-bucket
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: tempo-bucket
          key: AWS_SECRET_ACCESS_KEY
    - name: BUCKET_NAME
      valueFrom:
        configMapKeyRef:
          name: tempo-bucket
          key: BUCKET_NAME
    - name: BUCKET_HOST
      valueFrom:
        configMapKeyRef:
          name: tempo-bucket
          key: BUCKET_HOST
    - name: BUCKET_PORT
      valueFrom:
        configMapKeyRef:
          name: tempo-bucket
          key: BUCKET_PORT
  storage:
    trace:
      backend: s3
      s3:
        endpoint: $(BUCKET_HOST):$(BUCKET_PORT)
        bucket: $(BUCKET_NAME)
        region: us-east-1
        forcepathstyle: true
        insecure: true
  metaMonitoring:
    serviceMonitor:
      enabled: true
  tempo:
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 512Mi