rook-ceph:
  ingress:
    dashboard:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      host:
        name: admin-ceph.csepulveda.net
        path: /
        pathType: Prefix
      tls:
        - hosts:
          - admin-ceph.csepulveda.net
          secretName: admin-ceph-tls
      ingressclassName: nginx

  crds:
    enabled: true
  
  monitoring:
    enabled: false
  
  csi:
    enableRbdDriver: false
    enableCephfsDriver: false
    enableNFSDriver: false
    enableCephfsSnapshotter: false
    enableRBDSnapshotter: false
    enableVolumeReplication: false
  
  enableDiscoveryDaemon: true
  
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
