apiVersion: v2
name: gpu-operator
description: install gpu-operator
type: application
version: 25.5.0
appVersion: v25.3.1

dependencies:
- name: gpu-operator
  version: v25.3.3
  repository: "https://helm.ngc.nvidia.com/nvidia"
  alias: gpu-operator
