apiVersion: v2
name: gpu-operator
description: install gpu-operator
type: application
version: v24.3.0
appVersion: v24.3.0

dependencies:
- name: gpu-operator
  version: v24.3.0
  repository: "https://helm.ngc.nvidia.com/nvidia"
  alias: gpu-operator
