apiVersion: v2
name: gpu-operator
description: install gpu-operator
type: application
version: v23.9.1
appVersion: v23.9.1

dependencies:
- name: gpu-operator
  version: v23.9.1
  repository: "https://helm.ngc.nvidia.com/nvidia"
  alias: gpu-operator
