apiVersion: v2
name: garage
description: Install Garage S3-compatible storage
type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:
- name: garage
  version: "*"
  repository: "https://git.deuxfleurs.fr/Deuxfleurs/garage/raw/branch/main/scripts/helm"
  alias: garage