garage:
  # Replication mode
  replicationMode: 3
  
  # Number of replicas
  replicaCount: 3
  
  # Persistence configuration
  persistence:
    data:
      storageClass: iscsi
      size: 8Gi
    
  # Resources
  resources:
    requests:
      memory: 512Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 500m
  
  # Service configuration
  service:
    type: ClusterIP
    s3:
      api:
        port: 3900
      web:
        port: 3902
    admin:
      port: 3903
  
  # Ingress configuration
  ingress:
    enabled: true
    className: cilium
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      external-dns.alpha.kubernetes.io/target: router.csepulveda.net
    hosts:
      - host: s3.csepulveda.net
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: garage-s3-tls
        hosts:
          - s3.csepulveda.net
  
  # Web UI Ingress
  webIngress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: garage.csepulveda.net
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: garage-web-tls
        hosts:
          - garage.csepulveda.net
  
  # Admin ingress
  adminIngress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: garage-admin.csepulveda.net
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: garage-admin-tls
        hosts:
          - garage-admin.csepulveda.net
  
  # Monitoring
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
