apiVersion: apps/v1
kind: Deployment
metadata:
  name: truenas-proxy
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels: {app: truenas-proxy}
  template:
    metadata:
      labels: {app: truenas-proxy}
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: cfg
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: cfg
          configMap:
            name: truenas-proxy-cm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: truenas-proxy-cm
  namespace: monitoring
data:
  metrics.conf: |
    server {
      listen 8080;
      location /metrics {
        proxy_pass http://192.168.100.155:9100/metrics;
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: truenas-proxy
  namespace: monitoring
  labels:
    app: truenas-proxy
    job: node-exporter
spec:
  selector: {app: truenas-proxy}
  ports:
    - name: http-metrics
      port: 8080
      targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: truenas-proxy
  namespace: monitoring
  labels:
    release: prometheus
spec:
  jobLabel: job 
  selector:
    matchLabels: {app: truenas-proxy}
  namespaceSelector:
    matchNames: ["monitoring"]
  endpoints:
    - port: http-metrics
      interval: 15s
      path: /metrics
      metricRelabelings:
        - action: replace
          targetLabel: instance
          replacement: "192.168.100.155:9100"
        - action: replace
          targetLabel: nodename
          replacement: "truenas"