
apiVersion: v1
kind: Service
metadata:
  name: truenas-node-exporter
  namespace: monitoring
  labels:
    app: truenas-node-exporter
spec:
  ports:
    - name: http-metrics
      port: 9100
      protocol: TCP

---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: truenas-node-exporter-1
  namespace: monitoring
  labels:
    kubernetes.io/service-name: truenas-node-exporter
addressType: IPv4
ports:
  - name: http-metrics
    port: 9100
    protocol: TCP
endpoints:
  - addresses: ["192.168.100.155"]
    conditions:
      ready: true

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: truenas-node-exporter
  namespace: monitoring
  labels:
    release: prometheus  
spec:
  selector:
    matchLabels:
      app: truenas-node-exporter
  namespaceSelector:
    matchNames: ["monitoring"]
  endpoints:
    - port: http-metrics
      interval: 30s
      path: /metrics