democratic-csi:
  controller:
    driver:
      enabled: true
      image:
        registry: docker.io/democraticcsi/democratic-csi
        tag: next
  csiDriver:
    name: org.democratic-csi.nfs
  driver:
    existingConfigSecret: freenas-driver-config-nfs
    config:
      driver: freenas-api-nfs
  storageClasses:
  - allowVolumeExpansion: true
    defaultClass: false
    name: nfs
    parameters:
      detachedVolumesFromSnapshots: "false"
      fsType: nfs
    mountOptions:
      - noatime
      - nfsvers=4
    reclaimPolicy: Delete
    secrets:
      controller-expand-secret: null
      controller-publish-secret: null
      node-publish-secret: null
      node-stage-secret: null
      provisioner-secret: null
    volumeBindingMode: Immediate
  volumeSnapshotClasses:
  - name: nfs
    parameters:
      detachedSnapshots: "true"
