jellyfin:
  hostNetwork: true

  service:
    type: LoadBalancer

  persistence:
    config:
      pvc:
        enabled: true
        claimName: jellyfin-config
    media:
      pvc:
        enabled: true
        claimName: jellyfin-media