jellyfin:
  podAnnotations:
    ipam.cilium.io/ip-pool: multimedia-pool

  service:
    type: LoadBalancer

  persistence:
    config:
      pvc:
        enabled: true
        claimName: jellyfin-config
    media:
      pvc:
        enabled: true
        claimName: jellyfin-media